### ISSUE TITLE
Automate creation from scratch

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#101]
Right now when one creates a VM from scratch there is a need for manual input from a user e.g. click thought the macOS installation process. It will be great if we can automate the process and do the [recommended steps](https://github.com/cirruslabs/tart#creating-from-scratch) automatically.

```console
tart create --from-ipsw=latest --username=admin --password=admin latest
```

This way we can also start saving the username and password within the config to simplify UX for cases like `tart run --vnc latest` for example (can pre-fill username and password for screen sharing).

**Comment by trodemaster** [comment]
Building custom macOS VMs starting with a local ipsw file is my goal as well. See my existing packer template for x86 macOS VMs here https://github.com/trodemaster/packer-macOS-11

My approach would be similar for Applesilcon VMs. Which is to boot the VM and then use packer boot commands to complete the Apple Setup screens and ssh configuration so that packer could finish the customizations.

I'm unclear on what the username and password would do with the tart cli tool? Is that maybe overlapping with the packer boot commands function? Keep in mind apple likes to change those setup screens with major releases so could get messy if you bake that directly into tart.

**Comment by damonbreeden** [comment]
related: https://github.com/cirruslabs/macos-image-templates/pull/48

**Comment by trodemaster** [comment]
Using an MDM solution to push a profile to the VM Is an option.  I opened an issue with apple (FB10026741) asking them to add support for simply passing a profile to the VM via the virtualization framework directly bypassing the networking and MDM requirements. I'm not holding my breath on that one. But if others request the same thing it would help. 

Straight up building https://micromdm.io into tart would be a robust but likely overly complex solution. Tart and its packer plugin are really only missing a handful of features to enable building from scratch via VNC commands and existing techniques.

**Comment by fkorotkov** [comment]
@trodemaster agreed that your technique seems like the best option. We just haven't had time to look into your packer plugin. I briefly checked out the code but I'm not too familiar with the things there so need definitely a more thorough look 😅  Hopefully will find time next week.

**Comment by trodemaster** [comment]
Sounds good! I have posted a screen recording of the process on my blog which should help visualize what's happening with the boot command technique. It's the second video on this page. https://netjibbing.com/post/packer-macos-11/  Applesilicon macs boot directly into the setup screens so in that case, the boot commands would need to work their way through setup. Not ideal but doable.

**Comment by torarnv** [comment]
If we can boot into recovery mode, and run terminal commands from there (via synthetic key and mouse events sent to the VM), would that allow doing the setup entirely from the command line, so that the next time the OS boots normally it doesn't do the setup?

In any case, the logic of what to run or download/install via the synthesized events should probably be external to tart as much as possible, so that packer or other provisioning mechanisms can choose exactly how to do the setup?

**Comment by edigaryev** [comment]
This was implemented in https://github.com/cirruslabs/packer-plugin-tart/pull/21.

Packer templates that utilize this were introduced in https://github.com/cirruslabs/macos-image-templates/pull/55. While currently the templates don't disable lock screen and enable auto-login automatically, this is a target for further improvements as a part of https://github.com/cirruslabs/macos-image-templates/issues/56.
