### ISSUE TITLE
Support credentials helpers

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#167]
Will be nice to support [credentials helpers](https://docs.docker.com/engine/reference/commandline/login/#credential-helper-protocol). Can make Tart a bit smarter and check `$HOME/.docker/config.json` for the config`

Related issues: #166

**Comment by edigaryev** [comment]
Just a little clarification after we've discussed this with @fkorotkov: the main idea here is to re-use Google and Amazon credential helpers that the Docker uses to avoid manually calling `tart login`.

**Comment by remarkov** [comment]
It would be super awesome to prioritize this, if possible. We are about to provision quite a good amount of new machines with Tart. We use ansible for that and working with keychain over SSH is sometimes tricky. Instead of digging deep into Apple issues with manipulating keychains over SSH, it would be really nice to use a credential helper for Tart authorization and automate the whole thing easily.
