### ISSUE TITLE
Option to change disk size of a VM

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#17]
Need to investigate and option to grew VM's disk size.

**Comment by qbx2** [comment]
I don't think tart is for only packer, it should be very helpful if FAQ introduces how to do this using cli. I went through the source code and github to do it.
My answer:
```
$ truncate ~/.tart/vms/my-vm/disk.img -s 100g
```
[... tart run and ssh in to vm]
```
$ diskutil repairDisk disk0

$ diskutil apfs resizeContainer disk0s2 0

$ df -h ~
```

**Comment by iby** [comment]
@qbx2 thanks for that info! 🙏 A couple of small remarks for future generations:

Doing this in macOS host:

```sh
# Complains in Sonoma 14.5 and prints out command help:
# truncate ~/.tart/vms/my-vm/disk.img -s 100g

# This works:
truncate -s 100g ~/.tart/vms/my-vm/disk.img
```

Doing this inside macOS VM:

```sh
# Not sure if this is macOS 15 Sequoia (Beta 2) (vanilla image) or something else,
# but there's no disk0 for some reason – using disk1 worked perfectly.

# To see all partitions – we want the first one (internal, physical).
diskutil list

diskutil repairDisk disk1
diskutil apfs resizeContainer disk1s2 0
df -h ~
```

**Comment by myxal** [comment]
Hello, I'm somewhat new to tart and also have a few remarks:

- When using `truncate`, make sure you're growing the disk - otherwise you WILL lose data, and `truncate` will not warn you, it's not targeted at disks/images. There's `hdiutil resize -imageonly ...` which I'd suggest using in a script.
- The procedure posted by @qbx2 only works if you delete the recovery partition from the VM disk. The `disk0s2` refers to the "user" (OS + data) APFS container (the partition on the "physical" disk, as opposed to the APFS container synthesised disk), which is normally sandwiched between the iSCPreboot container and the Recovery container, as is common on Apple-Silicon Macs' internal disks (https://eclecticlight.co/wp-content/uploads/2021/12/bootdiskstructurem1monty.png)
- If you wish to preserve the recovery partition, `dd`-copy and a bit of legwork with Rod Smith's `gdisk` (or _a lot_ of legwork with the builtin `gpt`) can do that:
```
$ hdiutil attach -nomount  -readonly ~/.tart/vms/my-vm/disk.img 
...
/dev/disk4s3        	Apple_APFS_Recovery
$ sudo dd if=/dev/disk4s3 bs=2m of=~/.tart/vms/my-vm/recovery.raw
$ diskutil eject disk4
$ hdiutil attach -nomount ~/.tart/vms/my-vm/disk.img 
$ sudo gdisk /dev/disk4
> p (disk details and basic info about partitions)
> i 3 (details about 3rd partition)
> d 3 (delete 3rd partition)
> n... (create partition; number: 3, first sector: last usable on disk minus partition size in previous step, last sector: default, GUID: copy from previous step, 5263...)
> c 3 (change name what was in p output)
> x (expert's menu)
> c 3 (change partition unique GUID to what it was in p-step)
> w (write changes and exit)
$ sudo dd of=/dev/disk4s3 bs=2m if=~/.tart/vms/my-vm/recovery.raw
```

At this point I thought that I could even run the `resizeContainer` command from the host, but apparently VMs' Data volume is somehow encrypted ("Encrypted at rest") - I suppose there's no workaround, to acquire the unlock passphrase from within host OS?

**Comment by simonbs** [comment]
The following steps worked for me on macOS Ventura 14.5.

### From the host machine

1. Run `truncate -s 150g ~/.tart/vms/my-vm/disk.img` to increase the disk size to 150 GB. Replace 150 with the size you'd like to resize to. Truncating to a smaller image size may cause data loss.
2. Run the virtual machine with `tart run my-vm`.
3. Obtain the IP address of the virtual machine with `tart ip my-vm`.
4. SSH into the virtual machine with `ssh runner@{IP_ADDRESS}`.
5. Run `diskutil repairDisk disk0` on the virtual machine.
6. Shut down the virtual machine.
7. Run the virtual machine in recovery mode with `tart run my-vm —-recovery`.

### In the virtual machine running in recovery mode

1. Open the Terminal app.
2. Run `diskutil list` to identify the identifier of the volume named `Apple_APFS_Recovery`. We'll assume the identifier is disk0s3.
3. Erase the recovery volume with `diskutil eraseVolume free free disk0s3`.
4. Resize the primary APFS container with `diskutil apfs resizeContainer disk0s2 0`.
5. Shut down the virtual machine.

The disk space has now been increased.

**Comment by james-rant** [comment]
Be very wary following these steps to resize the VM container. I followed the steps and successfully resized the VM's disk space, but after doing so, I am now unable to update the OS on that VM. When I try I get an error from macOS saying "Unable to personalise the update" and it fails. And then when I tried from the command line, I noticed the actual error:

> Failed to find SFR recovery volume

So while this will enable you to increase the disk space, it results in being unable to update the OS. 

Is it possible to reinstate the recovery volume? Or will I have to create a new VM?

**Comment by iby** [comment]
@james-rant unless you've installed macOS from ISPW, the recovery volume would be removed from the start, see https://github.com/cirruslabs/tart/issues/889#issuecomment-2283709603. So, this is probably unrelated to resizing the disk.

**Comment by james-rant** [comment]
> [@james-rant](https://github.com/james-rant) unless you've installed macOS from ISPW, the recovery volume would be removed from the start, see [#889 (comment)](https://github.com/cirruslabs/tart/issues/889#issuecomment-2283709603). So, this is probably unrelated to resizing the disk.

To install to the VMs an IPSW is used, I believe. Someone correct me if I'm wrong? The recovery volume was definitely there prior to resizing the disk and OS updates worked prior to removing it, and the error specifically states it was because the recovery volume could not be found.

I'm not saying resizing the disk prevents updates from being possible, I'm saying the step of having to remove the recovery partition in order to resize the disk then prevents updates from being possible -- at least that's what I'm seeing in my case.

**Comment by iby** [comment]
Yes, they're all built from IPSWs in the first place. When you create a VM image yourself from scratch (you probably wouldn't forget [this](https://tart.run/integrations/vm-management/#creating-a-macos-vm-image-from-scratch) experience), there **would be** a recovery partition. But it's removed in prebuilt images to optimize their size – there would be no recovery partition if you're using a standard cloned image, e.g.:

```sh
tart clone ghcr.io/cirruslabs/macos-sonoma-base:latest sonoma-base
tart run sonoma-base
```

And you wouldn't be able to update a prebuilt cloned image either, whether before or after a disk resize. Hope this clarifies.

P.S. Greetings from Cardiff Bay! Small world.

**Comment by james-rant** [comment]
Ok, that was the information I was missing. I believe I installed from a standard ISPW, not a prebuilt one.

🏴‍󠁧‍󠁢‍󠁷‍󠁬‍󠁳‍󠁿 👋 !

**Comment by edigaryev** [comment]
By the way, if you use the [Packer builder for Tart VMs](https://github.com/cirruslabs/packer-plugin-tart), there's a [`recovery_partition` option](https://developer.hashicorp.com/packer/integrations/cirruslabs/tart/latest/components/builder/tart#optional:) that you can set to  to `relocate` to both (1) resize the disk and (2) avoid loosing the recovery partition if that's what you want.

**Comment by james-rant** [comment]
Thanks! I'll look into that!

**Comment by dataprolet** [comment]
> `# This works:`
> `truncate -s 100g ~/.tart/vms/my-vm/disk.img`

After running this command on MacOS 15.5 I'm trying to run the VM using `tart run vm` I get the following error:

> Error: Invalid disk image. The disk image format is not recognized.

**Comment by mrpippy** [comment]
At least with an ASIF format image on Tahoe, I found that `diskutil image resize` moves the recovery partition and resizes the main filesystem automatically:

```
% diskutil image resize --size 120g disk.img

[10% completed] Resizing disk image...
[20% completed] Moving recovery partition...
[27% completed] Resizing partition...
[90% completed] Resizing file system...
[90% completed] Fitting partition table to new disk size...
100% completed

.tart/vms/update-26.3-grown/disk.img resized successfully
```
