### ISSUE TITLE
Can not install via brew

### ISSUE THREAD

**Issue by cutiechi** [cirruslabs/tart#176]
![图片](https://user-images.githubusercontent.com/27606234/183893462-09b3ef26-9ff3-4ce5-92c0-3778e713f2f0.png)

**Comment by fkorotkov** [comment]
@cutiechi what's you macOS version? Do you also mind sharing output of `brew doctor`?

**Comment by cutiechi** [comment]
@fkorotkov 
![图片](https://user-images.githubusercontent.com/27606234/183899824-1c3ea5a6-66df-4531-8848-720896ac0e06.png)

**Comment by fkorotkov** [comment]
Oh. There might an issue that you are running on Intel and Tart is only supported for Apple Silicon. Seem this is a weird error that brew shows when it can't find what to do because of that [if statement](https://github.com/cirruslabs/homebrew-cli/blob/dc8848fa9539304558481fe505e31290f954b89c/tart.rb#L12). Let me see if we can do something about that.
