### ISSUE TITLE
Support for API to launch VMs

### ISSUE THREAD

**Issue by sanieldalib** [cirruslabs/tart#198]
Hey there, really great stuff with the Tart project! 

I was wondering if there are plans to support an API for launching and tearing down VMs from another service. Any advice on implementing something like this? My use case is trying to run a cluster of Tart hosts to spin up VMs.

**Comment by fkorotkov** [comment]
Hey @sanieldalib,

We don't have such plans on our own since it seems like a big investment to develop and especially support. Plus we don't have a particular use case for our usage. But if you or someone from the community willing to collaborate we've been thinking of having a Nomad plugin for that. Please check #201 and let me know if that is something that would work for you.

**Comment by edigaryev** [comment]
> Any advice on implementing something like this?

Tart has a pretty straightforward CLI and can be easily wrapped in a [Golang's `os/exec`](https://pkg.go.dev/os/exec), [Python's `subprocess`](https://docs.python.org/3/library/subprocess.html), etc. and further be exposed as an API.

The [Cirrus CLI](https://github.com/cirruslabs/cirrus-cli) actually [uses Tart this way](https://github.com/cirruslabs/cirrus-cli/tree/master/internal/executor/instance/persistentworker/isolation/tart), but doesn't completely expose this as an API, unfortunately.
