### ISSUE TITLE
Investigate how to isolate two tart VMs

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#20]
Seems by default Virtualization framework makes the network sharable. Let's see if we can isolate two VMs running simultaneously so one can't ssh into another.

**Comment by edigaryev** [comment]
> However, after the wraparound happens the internal DHCP-server breaks somehow and VMs start to assign themselves addresses [from the `169.254.0.0/16` range](https://en.wikipedia.org/wiki/Reserved_IP_addresses) and not from `192.168.64.0/24` range.

I've researched a bit more on this topic and it turns out that this is only partially true. The DHCP-server used in macOS is actually `bootpd(8)` and it's sources [are available publicly](https://github.com/apple-opensource/bootp).

The server can actually reclaim the expired IP-addresses from the pool by calling `DHCPLeases_reclaim()` function, but it will only do so when there are no more free IPs available (https://github.com/apple-opensource/bootp/blob/bd11fdd07f7b9b581e32d2e19e653101cb42c540/bootpd.tproj/dhcpd.c#L798-L800) and the reclamation will succeed only if there are expired entries that can be evicted from the pool.

So, the issue I've seen in https://github.com/cirruslabs/tart/issues/20#issuecomment-1116732505 was due to the fact that by default the lease interval is a day (86400 seconds) long, but the whole experiment was done probably under an hour.
