### ISSUE TITLE
File based lock on VM operations

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/tart#21]
Let's make sure that a user can't access VM from two simultaneous `tart` invocations. We can probably just put a lock file inside the VMs folder. Plus we can modify timestamp of the file upon a lock so we potentially can see when the VM was used last time. Might be useful for auto-pruning of VMs based on LRU concept.

**Comment by edigaryev** [comment]
I've started implementing this and realized that in the current state, in which there's no single daemon like `dockerd`, but instead multiple `tart` instances with the same access level that can run concurrently, the locking would create more problems that it'd solve.

Specifically, the complexities it'll bring to the codebase may outweigh the damage caused by issuing `tart delete` on a running instance.

What I propose at this point instead is to perform all writes consisting of multiple files into a temporary directory and then `rename(2)` these into their final destination. This will ensure that `tart create`, `tart clone` and `tart pull` would avoid inconsistent state.

@fkorotkov what do you think?

**Comment by fkorotkov** [comment]
Agreed that it can bring unnecessary complexity. I think the minimum we should do is to:
1. Clean up the vm directory in case of failure or Ctrl+C for `create`/`pull`. 
2. `clone` is already an atomic file system operation.
3. Print a nice error in case someone tries to `run` the same VM twice like `Vitual machine "latest" is already running with 192.168.65.124 IP`.

One other note is to maybe think of adding a file to the VM directory timestamp of which will represent time of the last operation with the VM. But something like that should be a part of #37 (we discussed that the lock files from this issue could play a role of the timestamp data).
