### ISSUE TITLE
Change disk size when using cirrus-cli

### ISSUE THREAD

**Issue by barkingfoodog** [cirruslabs/tart#224]
I'm running some automated testing with cirrus-cli that is using up all available disk space on the guest VM. Reading the README, it appears I'm stuck with the disk size provided by cirrus:

> Note: Cirrus CI only allows [images managed and regularly updated by us](https://github.com/orgs/cirruslabs/packages?tab=packages&q=macos).

And:

> **How to change VM's disk size?**
> You can choose disk size upon creation of a virtual machine:
> `tart create --from-ipsw=latest --disk-size=25 monterey-vanilla`

Since we clone an image to use with cirrus and not create it, we can't adjust the image size on boot. Is that right?

Looks like a previous discussion suggested using shared folders to use large files (e.g. Xcode) stored outside the VM:

* #44
* #13
* #211

Just wanted to confirm the design.

**Comment by edigaryev** [comment]
> > Note: Cirrus CI only allows [images managed and regularly updated by us](https://github.com/orgs/cirruslabs/packages?tab=packages&q=macos).

This limitation only applies when running tasks in the cloud. If you are running Tart locally either directly or via the Cirrus CLI, you can adjust the VM's disk size and then re-use that modified VM as a template multiple times.

> Looks like a previous discussion suggested using shared folders to use large files (e.g. Xcode) stored outside the VM:

Since recently you can specify the `--dir` option for `tart run` and thus avoid the need to expand the disk in some cases, yes. But you need a macOS 13 (Ventura) host for this.

There's also an issue (https://github.com/cirruslabs/cirrus-cli/issues/554) to support this in Cirrus CLI itself, which I'm expecting to resolve later this week.

**Comment by barkingfoodog** [comment]
Excellent, thank you for clarifying CLI can use a user-created image. That will be a great help to bake in pre-requisites using Packer.

Looking forward to upgrading to Ventura for Linux support, additional directories, and more. Exciting times!
