### ISSUE TITLE
tart ssh

### ISSUE THREAD

**Issue by tomjn** [cirruslabs/tart#304]
A command to open an SSH session with a named Tart VM, with optional authentication parameters

e.g.

```sh
tart ssh ubuntu
```

This is assuming the guest VM is already configured for SSH access, which may require user intervention.

It would also be useful to pass a command as an argument that then runs and exits, perhaps passing back a return code, e.g.

```sh
tart ssh ubuntu --command "echo 'hello world'"
```

**Comment by geerlingguy** [comment]
Note that some of the rationale would be to allow programs like Vagrant to log in easily. For Vagrant's preconfigured boxes, they are usually configured with a default admin user like `vagrant` with password `vagrant`, and SSH is set up to run on port 22 by default. macOS can even be configured to run SSH the same way, which is highly convenient for those of us who enjoy automating macOS with Ansible ;)

**Comment by fkorotkov** [comment]
Does `ssh ubuntu@$(tart ip ubuntu)` work for you?

**Comment by tomjn** [comment]
That's a promising start. For vagrant at least we'll want to be sure we can put a `vagrant` user in the VM before running this and that an SSH daemon is running and inside the VM, I imagine we'd do this via packer? Does the Tart packer fork play well with non MacOS VMs?

This is probably going to be the easiest route to running provisioners in Vagrant beyond the scripts to build an images/boxes that get packaged

**Comment by fkorotkov** [comment]
Since Tart itself is not storing information about user/password configured inside the VM, we can't do `tart ssh` and an integration will need to take care of it.

**Comment by TyceHerrman** [comment]
would you consider a credential-free helper that only resolves the VM address and delegates to the system OpenSSH client?

something like:
```console
tart ssh vm-name --user admin -- -A
# or, more narrowly:
tart ssh-config vm-name --user admin
```

Tart would not store usernames, passwords, private keys, or other guest credentials. `/usr/bin/ssh` would continue to manage OpenSSH configuration, identities, agent forwarding, known hosts, `ProxyJump`, `ControlMaster`, port forwarding, terminal behavior, and exit status. The helper could optionally wait for the VM address and port 22 with a bounded timeout.

This would complement rather than replace `tart exec` from #1074. `tart exec` would be the simpler option when the guest agent is sufficient. Delegating to OpenSSH covers standard SSH features such as agent forwarding, which is currently missing from `tart exec`
