### ISSUE TITLE
tart clone duplicates the UUIDs and can lead to undefined behavior of VMs

### ISSUE THREAD

**Issue by uttie-huntress** [cirruslabs/tart#311]
Apple's Virtualization.Framework does not support clone out of the box and presently `tart clone` copies the parent VM directory into the cloned vm.

This poses a problem of having two machines running with duplicate MIDs, which is [stated in the documentation](https://developer.apple.com/documentation/virtualization/vzmacplatformconfiguration/3816084-machineidentifier#:~:text=Running%20two%20VMs%20concurrently%20with%20the%20same%20identifier%20results%20in%20undefined%20behavior%20in%20the%20guest%20operating%20system.) to lead to undefined behavior.

The immediate problem this poses is that the generated UUIDs in both machines are the same, and creates a problem for consumers expecting it to the unique.

A secondary problem I have seen is that certain settings (like disabling SIP) on a cloned VM seem to percolate to the parent's VM. (I'd like to test this further to get a consistent repro)

The request is to investigate and fix it in a way that the generated MIDs are unique and don't lead to undefined behavior
The [Eclectic Light article](https://eclecticlight.co/2022/08/24/virtualisation-on-apple-silicon-macs-11-machine-identities/) has a good detail about this investigation

References: 
* https://eclecticlight.co/2022/08/24/virtualisation-on-apple-silicon-macs-11-machine-identities/
* https://developer.apple.com/documentation/virtualization/vzmacplatformconfiguration/3816084-machineidentifier

**Comment by pthexton** [comment]
If a solution to this is ever added, I'd like the option to retain the current behaviour.  We use tart for automated testing of our software suite where we make use of an MDM configuration profile sent to the base VM image to facilitate automatic enablement of our software (as opposed to requiring admin user interaction to approve system extensions and full disk access), we don't want to run in to issues where the mobileconfig deployed to the VM may somehow invalidated due to the underlying UUID being changed

**Comment by fkorotkov** [comment]
I don't think we ever plan to implement this behaviour unless something will break.
