### ISSUE TITLE
VM created can't access company internal network via VPN

### ISSUE THREAD

**Issue by hokadiri** [cirruslabs/tart#384]
Hi. I connect to my internal network via VPN. 
On my host machine i'm able to access internal sites. But on the tart vm I'm unable to. 

I believe my vpn interface is `utun3` when i do:
```
 tart run --net-bridged utun3  ventura-base:14.2
Error: no bridge interfaces matched "utun3", available interfaces: en0 (or "Wi-Fi")
```

How can i configure and run the tart VMs so that from within it i can access internal company network?

**Comment by edigaryev** [comment]
Unfortunately, due to how Apple's [`Virtualization.Framework`](https://developer.apple.com/documentation/virtualization) and [`vmnet.framework`](https://developer.apple.com/documentation/vmnet) configure NAT, the VM can only properly communicate with the hosts reachable through default routes that have gateways, you can verify this by running the following command as root:

```shell
pfctl -s nat -a "com.apple.internet-sharing/shared_v4"
```

This will show you to which interfaces the automatically created `nat` rules apply.

In your case it's likely that the company's VPN does install specific routes to its internal subnets, but no general default route (to prevent extraneous traffic bills, server overload, etc.), and thus there's to `nat` rule for that VPN interface.

Regarding the `--net-bridged`, it's also seems to be limited by the `Virtualization.Framework` to non-virtual interfaces: works for Ethernet and Wi-Fi, but not VPN.

**Comment by hokadiri** [comment]
Hmm, i can't seem get it to work.

With Ethernet:
```
➜  tart run --net-bridged en7 ventura-base:14.2
Error: Invalid virtual machine configuration. Using VZBridgedNetworkDeviceAttachment in a process that lacks the “com.apple.vm.networking” entitlement.
```

With Wifi:
```
➜  tart run --net-bridged "Wi-Fi" ventura-base:14.2
Error: Invalid virtual machine configuration. Using VZBridgedNetworkDeviceAttachment in a process that lacks the “com.apple.vm.networking” entitlement.
```

**Comment by fmoc** [comment]
I'm in a similar situation and hope for a fix. I'm using OpenVPN on the host system. The OpenVPN server pushes some specific routes, regular traffic doesn't go through the VPN by default. The routing table looks similar to this:

```sh
% sudo netstat -rn         
Routing tables

Internet:
Destination        Gateway            Flags           Netif Expire
default            <gateway>          UGScg             en0       
default            link#20            UCSIg       bridge100      !
10.xx.4/24         172.yy.zz.1        UGSc            utun3       
10.xx.5/24         172.yy.zz.1        UGSc            utun3       
127                127.0.0.1          UCS               lo0       
127.0.0.1          127.0.0.1          UH                lo0       
[...]
169.254            link#6             UCS               en0      !
172.yy             172.yy.zz.1        UGSc            utun3       
172.yy.zz/22       172.yy.zz.99       UGSc            utun3       
172.yy.zz.99       172.yy.zz.99       UH              utun3       
192.168.64         link#20            UC          bridge100      !
192.168.64.1       <some mac>         UHLWI             lo0       
192.168.64.2       <some mac>         UHLWIi      bridge100    187
224.0.0/4          link#6             UmCS              en0      !
224.0.0.251        <some mac>         UHmLWI            en0       
224.0.0.251        <some mac>         UHmLWIg     bridge100       
255.255.255.255/32 link#6             UCS               en0      !
```

I'd consider routing everything through the VPN if that fixed the issue, but it smells like a bad workaround... I really don't want to run a VPN client in the VMs given the host is in the VPN already.

P.S.: I also tried `--net-softnet`, but to no avail. Bridging to the VPN interface doesn't work as described above (and wouldn't make sense, since it can't route Internet traffic at the moment anyway).

**Comment by nathreed** [comment]
I also ran into this with an OpenVPN client and fixed it with something like the following:

- `sudo sysctl -w net.inet.ip.forwarding=1`
- Then set up NAT using `pf`. Use the guide at https://openvpn.net/cloud-docs/enabling-routing-nat-on-macos/ except for the rule use `nat on utun3 from bridge100:network to any -> utun3` where utun3 is your VPN interface. Make sure some VM is running so you have bridge100.

**Comment by fmoc** [comment]
Doesn't seem to work reliably here. I can get some packets through the VPN, but this seems to make the entire VM lag (I'm connected over SSH, there's no output for seconds, and Ctrl-C won't terminate immediately but takes a couple of seconds, too).

**Comment by fmoc** [comment]
@nathreed can you post the exact commands you were using, please?

**Comment by fmoc** [comment]
I also tried to apply https://github.com/metalgold/docker-m1-vpn-workaround as mentioned in https://github.com/docker/for-mac/issues/5208, but unfortunately to no avail. Seems like Docker have resolved the issue in the meantime, though, since they no longer list VPN problems on their [known issues page](https://docs.docker.com/desktop/troubleshoot/known-issues/). I used both `ping` as well as `curl` for testing, since Docker mention the former may not work reliably as a check, but neither works, so I can only assume the problem persists.

**Comment by fmoc** [comment]
Ok, so here is what seems to work in my case:

```sh
# enable ip forwarding if needed 
sudo sysctl -w net.inet.ip.forwarding=1
# dump existing rules
sudo pfctl -s nat -a "com.apple.internet-sharing/shared_v4" > pf.conf
# add rule as provided by @nathreed 
echo "nat on utun0 from bridge100:network to any -> utun0" >> pf.conf
# apply complete rule set
sudo pfctl -a com.apple.internet-sharing/shared_v4 -N -f pf.conf
```

Thanks @nathreed for the rule! It took me quite a while to figure this out. macOS NAT isn't documented very well, apparently. The combination of the existing rules with the new rule allows both VPN and non-VPN connections to be forwarded by the host as expected.

**Comment by fkorotkov** [comment]
It seems it will be fixed once we repackage Tart as Desktop App with embedded provisions profiles so Bridged Network is working. Closing it as it will be fixed in ##243 and #305 receptively.

**Comment by fmoc** [comment]
Not necessarily. As pointed out in https://github.com/cirruslabs/tart/issues/384#issuecomment-1402647506, our VPN is supposed to be used for specific routes only. Bridging the VM to the VPN interface means losing the connection to the Internet, unless I'd configure bridging to more than one interface and could set up the routes accordingly (but that would likely have to be done manually, which is less than ideal given the VPN server pushes the routes).

In my opinion, VMs should use NAT by default. All connections should work just like on the host. This is how it's done in most other hypervisors, too (including QEMU/KVM and VirtualBox).

**Comment by fmoc** [comment]
I'd like to add some more details. Over time, additional NAT rules are added, reason unknown. These break access to the host's VPN. I have no idea why this happens.

```sh
nat on en0 inet from 192.168.64.0/24 to any -> (en0:0) extfilter ei
no nat on bridge100 inet from 192.168.64.1 to 192.168.64.0/24
#nat on utun0 inet from 192.168.64.0/24 to any -> 172.xx.yy.dd
#nat on utun0 inet from 192.168.64.0/24 to any -> 172.xx.yy.ee
#nat on utun0 inet from 192.168.64.0/24 to any -> 172.xx.yy.ee
#nat on utun0 inet from 192.168.64.0/24 to any -> 172.xx.yy.ee
nat on utun0 from bridge100:network to any -> utun0
```

The commented out rules need to be removed from the system to restore access. They are not there when the VM has just been created and started.
