### ISSUE TITLE
GitLab Runner Extension

### ISSUE THREAD

**Issue by mschmieder** [cirruslabs/tart#470]
Hello,

First of all I wanted to congratulate you on this great tool, it really helps streamlining OSX CI/CD work!
While you already provide a number of integrations, the one that I needed most was missing, the GitLabCI integration. I did take the opportunity to write a GitLab Runner Extension that can be used to integrate `tart` natively into the GitLab ecosystem,

I'm writing this here for awareness, as this might be a feature more people are looking for. Please have a look here.
https://gitlab.com/schmieder.matthias/gitlab-runner-tart-driver

It's in early stages and most likely will need some improvements over time, but it's already fully functional.
It does provide

- Auto Login to GitLab Registry
- Custom Registry Integration
- Auto resource management
- Concurrency

**Comment by fkorotkov** [comment]
Oh, wow! Thank you, @mschmieder! Thank you for working on this! Seems great minds think alike! 

I did pretty much the same but in Go: https://github.com/cirruslabs/gitlab-tart-executor. There was a [GitLab Feature Request](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29319) for quite a while to add such an executor. @theoriginalgri  even created an MPV with bash scripts [here](https://github.com/Conntac/gitlab-runner-tart). I decided to productionaize the idea in Go because it simplifies the installation by having just a self-contained binary that you can pass arguments to. Very similar to what you did in Python!

 I wonder if you'd like to collaborate on the Go one? Seems the functionality of both is very similar.
