### ISSUE TITLE
Allow deleting local images older than N days

### ISSUE THREAD

**Issue by sjchmiela** [cirruslabs/tart#542]
The way I understand it, `tart prune` right now only allows pruning [remote images and IPSW cache](https://github.com/cirruslabs/tart/blob/e8dbb86fc097eb2e2712a1391983703285fc24b6/Sources/tart/Commands/Prune.swift#L124), _not_ local images.

Would it make sense to allow pruning local images too? Say, I'm building images on every commit in CI and after I build a fresh one I want to delete all older than 3 days (that aren't running, obviously).

It seems `VMStorageLocal` would only need to implement `PrunableStorage` (filtering out running ones) and `VMStorageLocal` would need to `updateAccessDate` in [`open`](https://github.com/cirruslabs/tart/blob/e8dbb86fc097eb2e2712a1391983703285fc24b6/Sources/tart/VMStorageLocal.swift#L14) (as does its OCI equivalent)?

What do you think?

**Comment by fkorotkov** [comment]
I guess we can add something like `--source` argument similar to what `tart list` has. By default it will be equal to `oci`. @edigaryev do you have any thoughts on that?

**Comment by edigaryev** [comment]
@fkorotkov I think that `tart prune` is currently somewhat cache-specific, perhaps a better and a more logical command for this would be `tart delete`?

**Comment by fkorotkov** [comment]
Agreed, it might also complicate things when we'll add caches for resumable `tart pull`s. 🤔 

@sjchmiela can you maybe include something like date in the name of the temporary VMs and clean them via a script? Here is a script that will keep only 3 the most recent VMs (change `+4` in `tail` to control the amount) and will delete everything else.

```bash
tart list --source=local --format=json | jq --raw-output '.[] | .Name' | sort -r | tail -n +4  | xargs tart delete
```

**Comment by sjchmiela** [comment]
Hmm, yea, maybe we can use that. My suggestion:
- uses access date, not create date (as using timestamp in name would), probably this doesn't matter in this CI/CD case,
- allows removing images by age more easily (arguably, still possible manually in the removing script).

Thanks!

**Comment by fkorotkov** [comment]
Do I understand it correctly that you only build a VM once and push it right away to be consumed in a separate step right after? In that case it seems you just want to be able to see if a particular image is available remotely and in case of a "miss" build it and push it. And then you can delete it right away.

Does having something like `tart manifest inspect <REMOTE_IMAGE>` solve the issue for your use case? We think pruning local images is a bit concerning because we can't be sure if deleting a particular image is safe. Was it already pushed? Does it have any usefull information? If it was cloned from a remote image, does it have any modifications? 

We can also add the access time in the `json` output of `tart list` so people can customize logic for deletion and have full control and responsibility of the deletion process.

**Comment by sjchmiela** [comment]
> Do I understand it correctly that you only build a VM once and push it right away to be consumed in a separate step right after? In that case it seems you just want to be able to see if a particular image is available remotely and in case of a "miss" build it and push it. And then you can delete it right away.

Actually, you're correct!

> Does having something like `tart manifest inspect <REMOTE_IMAGE>` solve the issue for your use case? We think pruning local images is a bit concerning because we can't be sure if deleting a particular image is safe. Was it already pushed? Does it have any usefull information? If it was cloned from a remote image, does it have any modifications?

Yea, what I'll do instead is:
- build and push the image (with `--populate-cache`)
- delete the local equivalent immediately (later only use the OCI cache)
- prune local OCI cache with `prune --older-than` ([related](https://github.com/cirruslabs/tart/pull/549))
- prune remote images from Docker Registry some other way ([would be helpful](https://github.com/cirruslabs/tart/pull/551))

> We can also add the access time in the `json` output of `tart list` so people can customize logic for deletion and have full control and responsibility of the deletion process.

That would be nice, I took a stab at it [here](https://github.com/cirruslabs/tart/pull/550).

**Comment by edigaryev** [comment]
> I think that `tart prune` is currently somewhat cache-specific, perhaps a better and a more logical command for this would be `tart delete`?

I was wrong about that: it's less logical to implement such functionality in `tart delete` because (1) `tart delete` removes both local and OCI images, and adding prune functionality to it would duplicate the same functionality from `tart prune` and (2) adding local VM pruning ability in `tart prune` results in more DRY code, because all we need is there already.

PR: https://github.com/cirruslabs/tart/pull/557.
