### ISSUE TITLE
Consider hosting official Linux images?

### ISSUE THREAD

**Issue by geerlingguy** [cirruslabs/tart#624]
Under the Packages page (https://github.com/orgs/cirruslabs/packages), right now there are a number of macOS images, but no official Linux images. This means to run a Linux VM inside Tart, I have to spend a bunch of time installing Linux, or build and host my own package.

Is it possible we could get one or more official Linux images hosted on GitHub Packages? Maybe Ubuntu only for starters, or Ubuntu and Debian (or maybe figure out what is most popular and pick the top two or three distros).

**Comment by fkorotkov** [comment]
There is an Ubuntu one! https://github.com/cirruslabs/tart/pkgs/container/ubuntu

But we don't have a process of regularly updating them similarly to what we have in https://github.com/cirruslabs/macos-image-templates

Maybe we should create similar automations. We haven't invested time before since there wasn't as much interest in Linux images as in macOS ones.

**Comment by geerlingguy** [comment]
@fkorotkov I think it may help boost adoption of Tart for those of us looking to automate certain kinds of local testing. I've been evaluating Tart vs UTM vs Lima for my own use, as I need something able to be scriptable, and with a network interface I can reach from the host (see: https://github.com/geerlingguy/ansible-for-devops/issues/404#issuecomment-1747846798).

I've had trouble installing Ubuntu Server for aarch64 on Tart though, but it would be nice to have prebuilt images for Linux in general, just saves a bunch of time testing out the tool :)

**Comment by geerlingguy** [comment]
I notice you also have a Packer plugin, with [docs here](https://github.com/cirruslabs/packer-plugin-tart/blob/main/docs/builders/tart.mdx); it has some instructions for macOS, but I may also be able to host some Linux images with a little guidance too (if you would rather not maintain the packages more or less 'officially'...).

I think it would be amazing if Tart could work with Fedora, Ubuntu, Debian, and maybe Rocky Linux or AlmaLinux so I could use them all for both local and cloud testing of Linux automation. (And some Mac automation, which you seem to have well covered already!).

**Comment by fkorotkov** [comment]
Please checkout [this folder with Linux examples](https://github.com/cirruslabs/packer-plugin-tart/tree/main/example/linux). Sorry I forgot to mentioned it initially!

We have people using Tart for Linux but it seems there are quite a few unique use cases these people use Tart for. Plus we ourselves don't use Linux VMs that much yet. That's why the documentation is a bit lagging but I think Tart might cover all your cases and we'll be happy to help with any issues.

**Comment by edigaryev** [comment]
We now have the [following images available](https://github.com/orgs/cirruslabs/packages?repo_name=linux-image-templates) for Tart:

* Ubuntu
  * `22.04`
* Debian
  * `bookworm`
* Fedora
  * `38`

The images are updated weekly and you can find the blueprints used for building them in the [`cirruslabs/linux-image-templates` repo](https://github.com/cirruslabs/linux-image-templates).
