### ISSUE TITLE
Lost older release binaires

### ISSUE THREAD

**Issue by jerrymarino** [cirruslabs/tart#629]
Good afternoon, thanks for all of the great work you've done with Tart! I maintain some build automation which relied on github release binaries of tart for tags < v 1.0 and recently observed that the binaries were no longer available. For instance: https://github.com/cirruslabs/tart/releases/download/0.14.0/tart is MIA 

I was curious if you planned to re-host them or other reasons we might not want to use the older cuts of it? At the EOD we may eventually update to newer version but still pull from the release urls to this day.

**Comment by luispadron** [comment]
+1, this seems to have been changed as of a few days ago

**Comment by fkorotkov** [comment]
Hey @jerrymarino, we removed the released binaries prior to `1.0.0` version because they were signed and notarized with my personal developer account. For `1.0.0` release we moved to a company one.

I'm not planning to renew my personal Developer Account in May and our understanding is that these binaries will stop working if anyone had them still installed. I'm sorry it affected you but hopefully it didn't break things in runtime for you like it could've happened in May.

Is there any chance you can upgrade? The CLI interface should be pretty much the same. The big thing is a [different license for `1.0.0`+](https://tart.run/blog/2023/02/11/changing-tart-license/). If your usage is above the limit and the license is not suitable for your company, please email support and we'll get you a **temporary license for free** so you are not blocked.

Once again sorry the inconveniences as we didn't expect 1+ year old version still be in use.
