### ISSUE TITLE
handle right click and touch pad gesture in mac books

### ISSUE THREAD

**Issue by anjannath** [cirruslabs/tart#66]
Hi, thanks for this amazing tools, i am using `tart` to test some isolated build of c++ programs locally, and found that i wasn't able to send a right click using the usual two-finger click in the vm.

**Comment by fkorotkov** [comment]
I'm glad your are liking Tart!

Similar to #14 it's not possible at the moment from the builtin UI because `VZVirtualMachineView` that is provided by Apple is not supporting it.

As a workaround you can use VNC and connect via Screen Sharing application. For that you need to run `tart run --no-graphics VM-NAME` and then in a separate terminal you can run `tart ip --wait VM-NAME` to get a local IP address to use in for screen sharing.

Note that if you are using one of our images then Screen Sharing is already configured and username/password for authentication is admin/admin. If you are building your own virtual machine from scratch don't forget to follow our [recommended setup](https://github.com/cirruslabs/tart#creating-from-scratch) to enable screen sharing.

**Comment by fkorotkov** [comment]
With Tart 0.6.0 the above workaround can be simplified to `tart run --vnc VM-NAME`.
