### ISSUE TITLE
List / Search templates/images cli command?

### ISSUE THREAD

**Issue by goodwillcoding** [cirruslabs/tart#666]
Maybe i am not seeing but it seems like there is no command to search for available templates/images for the CLI?

**Comment by edigaryev** [comment]
Unfortunately, that wouldn't be too practical, because there can be an infinite number of OCI registries hosting Tart VM images, and the most popular of them are unlikely to support `_catalog` API method, which allows listing/searching the available manifests (there are some discussions, though, https://github.com/opencontainers/distribution-spec/issues/71 and https://github.com/opencontainers/distribution-spec/issues/222).

As for the VM images created by Cirrus Labs, I think we can improve the related documentation them on the website, so I've created #674 to address that.
