### ISSUE TITLE
Support Intel Macs

### ISSUE THREAD

**Issue by aw1cks** [cirruslabs/tart#67]
Is there any possibility for Intel Macs in the future? Being able to do application testing across multiple OS versions on both Intel & M1 would be killer! Right now it requires multiple physical machines.

**Comment by fkorotkov** [comment]
Unfortunately, we are bounded by what Apple's [`Virtualization.Framework`](https://developer.apple.com/documentation/virtualization) is providing to us. We might add Intel support along the side of Linux support (#62) but I don't believe `Virtualization.Framework` will ever support Intel for running macOS. But I don't think we'll ever be able to run both platforms on one machine. 😪

**Comment by aw1cks** [comment]
That's a real shame! Thanks for the explanation.

**Comment by edude03** [comment]
Hm? I'm confused, @fkorotkov doesn't `Virtualization.framework` support both? I took a quick look at the link and it says 

> The Virtualization framework provides high-level APIs for creating and managing virtual machines (VM) on Apple silicon and Intel-based Mac computers

What am I misunderstanding?

**Comment by fkorotkov** [comment]
@edude03 Linux is supported for both Intel and Apple Silicon but macOS is only available on Apple Silicon. If we'll add Linux support as part of #62 we might build Tart for Intel as well.

But macOS VMs will not work on Intel because [`VZMacOSBootLoader` is only for Apple Silicon](https://developer.apple.com/documentation/virtualization/vzmacosbootloader).
