### ISSUE TITLE
"tart clone" stuck at 0%

### ISSUE THREAD

**Issue by NavpreetDevpuri** [cirruslabs/tart#680]
I tried to use `tart clone` to make a VM but it is just stuck at 0% for so long, 

```
tart clone ghcr.io/cirruslabs/macos-sonoma-base:latest sonoma-base
pulling manifest...
pulling disk (18.2 GB compressed)...
0%
```

**Comment by edigaryev** [comment]
Unfortunately, the progress is not very granular at the moment. We're only incrementing the percentage you see for each new chunk pulled (roughly `500 MB`), so it goes from 0% to like 4-6%.

You can check the exact speed [in the Activity Monitor](https://support.apple.com/en-am/guide/activity-monitor/actmntr1006/mac) by switching to `Network` tab and searching for the `tart` process.

**Comment by umlaeute** [comment]
i'm seeing a similar issue here: running `tart clone ghcr.io/cirruslabs/macos-monterey-vanilla:latest test` simply times out.

i've been running this a couple of times today, and I think the longest run took 1½ hours and it stayed at `0%`(!) - so I eventually killed the process.

The internet connectivity of the machine is fine (and i was able to download the `macos-sonoma-vanilla` and `macos-ventura-vanilla` images without problems.

since I run these commands via ssh on a remote machine, I unfortunately cannot access the *Activity Monitor* for more details.

it would be nice if we could instrument the `pull` a bit, e.g.:
- add a `--verbose` with more printout during operation
- add a `--chunksize` parameter to try different/smaller chunks (hopefully getting updates more often)
- react on `SIGUSR1` and print info about what is currently going on

**Comment by umlaeute** [comment]
> since I run these commands via ssh on a remote machine, I unfortunately cannot access the *Activity Monitor* for more details.

however, i *can* install `iftop` (via homebrew), which shows that my throughput varies between 200Mb and 5Mb (and downloading 16GB at 5Mbit should take about 10 hours, so no wonder that it takes ages.

unfortunately the files are also only updated once a complete chunk has been downloaded (otherwise the filesize would be an easily accessible metric for progress)
