### ISSUE TITLE
Error: ShouldBeAtLeastOneLayer

### ISSUE THREAD

**Issue by prologic** [cirruslabs/tart#719]
I'm not sure how to debug this :/

```console
$ tart clone ghcr.io/cirruslabs/ubuntu:latest ubuntu
pulling manifest...
Error: ShouldBeAtLeastOneLayer
```

**Comment by edigaryev** [comment]
Hello James 👋 

It seems that you've installed Tart from [Homebrew Core](https://formulae.brew.sh/formula/tart#default), and the version available there was published [almost a year ago](https://github.com/cirruslabs/tart/releases/tag/0.38.0).

There were countless improvements since then, including the [Improved format for fast and efficient pulls from remote OCI-registry](https://github.com/cirruslabs/tart/pull/589), which results in the lack of backwards-compatibility that you're seeing.

Please consider [installing Tart from our Tap](https://tart.run/quick-start/):

```shell
brew install cirruslabs/cli/tart
```

**Comment by prologic** [comment]
Thanks!
