### ISSUE TITLE
Adhere to XDG Base Directory Specification

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/tart#765]
I'd like `tart` to adhere to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), by e.g. placing downloaded images into `$XDG_CACHE_HOME` instead of cluttering home directory.

**Comment by edigaryev** [comment]
The main reason why the `.cache` directory is currently located in `~/.tart` is that there's a [`TART_HOME` environment variable](https://github.com/cirruslabs/tart/issues?q=is%3Aissue+TART_HOME) which allows users to conveniently relocate their VMs (including the downloaded OCI VMs, which are stored in `.cache`) and run the Tart from a separate disk (e.g. SSD).

Splitting the `~/.tart` from the `~/.tart/cache` is not be possible in this scenario because Tart relies on APFS zero-copy mechanism to copy the OCI VMs to the local VM storage, which does not work across the filesystem boundary.

What are you trying to achieve with this?

As far as I know, there are not too many apps adhering to XDG on macOS (compared to Linux), including the macOS itself.

**Comment by torarnv** [comment]
macOS is not a [Freedesktop](https://www.freedesktop.org/wiki/) platform, so I don't think it makes sense for Tart to pick up the various `XDG_` environment variables.

**Comment by fkorotkov** [comment]
Agreed with both points. Closing since we are not planning to support it.
