### ISSUE TITLE
Failed to suspend the VM: Invalid virtual machine configuration. Unsupported console device in configuration.

### ISSUE THREAD

**Issue by sc0rp10** [cirruslabs/tart#803]
Hi, constantly getting this error when trying to suspend any VM:

```
$ tart clone ghcr.io/cirruslabs/macos-sonoma-vanilla:14.4.1 foobar
pulling manifest...
pulling disk (16.0 GB compressed)...
100%
pulling NVRAM...

$ tart run foobar
# in the second terminal I ran `tart suspend foobar`
Failed to suspend the VM: Invalid virtual machine configuration. Unsupported console device in configuration.

$ tart --version
2.9.0
```

Also I have a question: is there a way to stop VM gracefully - without failing with a `CancellationError` the `tart run command`? I'm trying to build an API-wrapper for Tart and at the moment it's impossible to distinguish where the error is and where the graceful VM stop is because both of them produce the same error. I thought that I can suspend VM and then stop it - and the `tart run` command will get different error, but unfortunately it doesn't work as I posted below.

**Comment by edigaryev** [comment]
> Hi, constantly getting this error when trying to suspend any VM:

This is a limitation of `Virtualization.Framework` where it does not support suspending a VM with certain devices.

To disable these devices you can pass the `--suspendable` flag to `tart run`.

>Also I have a question: is there a way to stop VM gracefully - without failing with a CancellationError the tart run command?

You can do this by shutting down the guest from within it, e.g. by running `sudo halt` command in Terminal or over SSH.

We've opted not to do clean shutdowns because otherwise there would be a GUI pop-up that is burdensome to automate (you can check this yourself by clicking `Control → Request Stop` in `tart run` GUI menu):

<img width="1136" alt="Screenshot 2024-04-24 at 10 59 15" src="https://github.com/cirruslabs/tart/assets/85709/f735cf2a-5142-4f17-9636-1381d33a3d82">

In your API-wrapper you could probably distinguish the point of time where the `tart stop` was invoked. Before that time, `tart run` exits should be considered premature and an error should be reported.
