### ISSUE TITLE
Linux VM stops running with the --net-bridged option when used with --vnc

### ISSUE THREAD

**Issue by adit-s** [cirruslabs/tart#810]
tart version: 2.9.0
Mac OS: Sonoma 14.4.1
Guest VM OS: Ubuntu 23.10 (with KDE Desktop)

Issue summary: 
Running a linux VM with the --vnc & --net-bridged options, the machine starts and runs for about a minute and then exits with a message IPNotFound().
Running the same without the --vnc works normally with no errors.

Command syntax:
/usr/local/bin/tart.app/Contents/MacOS/tart run --vnc --net-bridged="Wi-Fi" 2310-desk
With a statically assigned local IP on the VM (applied using /etc/netplan).

Any ideas or feedback on what could be the reason for the issue and suggestions to fix it would be appreciated.

Thanks,
Adit

**Comment by edigaryev** [comment]
Unfortunately `--net-bridged` support for non-macOS VMs is not that great, because there's no easy way to obtain the VM's IP address as the DHCP server that assigns the VM's IP becomes external to Tart.

You might want to try installing Samba, which includes the [NetBIOS name server](https://www.samba.org/samba/docs/current/man-html/nmbd.8.html) that exhibits the same behavior as macOS and populates the ARP table of the host OS:

```
sudo apt-get install samba
```

**Comment by edigaryev** [comment]
I've also found an issue with how we choose the IP-address resolver when using both `--net-bridged` and `--vnc`, this should be fixed in https://github.com/cirruslabs/tart/pull/811.

**Comment by adit-s** [comment]
Confirming the issue is resolved in 2.10 (and I didn't need to install samba).

**Comment by rahb3rt** [comment]
@edigaryev I tried doing this today and had problems using VNC to go into VM. But I can open up the VM without vnc. Any thoughts on this
