### ISSUE TITLE
Trackpad system preferences missing

### ISSUE THREAD

**Issue by galderz** [cirruslabs/tart#856]
Trying out `tart run sonoma-base` and can't see a way to configure the Trackpad in the system preferences in the VM. The Trackpad option does not appear in the system preferences. Can the natural scrolling and other trackpad options be configured some other way?

**Comment by fkorotkov** [comment]
In #843 we dropped support for Monterey VMs because Sequoia VMs are crashing if there is `VZUSBScreenCoordinatePointingDeviceConfiguration` which seems lead to the issue.

While I don't see the preferences visually it seems I can search for them:

<img width="1022" alt="Screenshot 2024-07-10 at 9 03 39 AM" src="https://github.com/cirruslabs/tart/assets/989066/e66f6667-885d-46fd-8371-b7a6b3132274">

Is it the seeings you are looking for?

**Comment by galderz** [comment]
I saw those but couldn't see how to change "Natural scrolling" option.
