### ISSUE TITLE
macOS 12.6 upgrade is failing: Failed to personalize the software update. Please try again.

### ISSUE THREAD

**Issue by iby** [cirruslabs/tart#889]
I'm running macOS 12.5.1 (21G83):

```sh
tart clone --concurrency 10 ghcr.io/cirruslabs/macos-monterey-base:latest mon
tart run mon --dir=Development:~/Development --vnc
```

And trying to upgrade to the latest 12.7.6 version, but the update is failing with the following:

![image](https://github.com/user-attachments/assets/4a7b1f91-df45-4882-9886-9435ca9c435c)

Non-system updates seem to be working. I also checked this with UTM (installed from 12.6 IPSW), and everything works there. Feels like this might be VM-config related?

I couldn't find any references to tart, is this something known / fixable?

**Comment by edigaryev** [comment]
This is likely due to the fact that `ghcr.io/cirruslabs/macos-*` VM images have their recovery partition removed to save space and bandwidth, see https://github.com/cirruslabs/tart/discussions/631 for a similar report.

Installing from IPSW or using [Packer builder for Tart VMs](https://developer.hashicorp.com/packer/integrations/cirruslabs/tart/latest/components/builder/tart)'s `recovery_partition` option should produce updateable VM images.

**Comment by iby** [comment]
Aha, awesome, thanks for pointing in the right direction! 🙏
