### ISSUE TITLE
VMs are not actually stopping/stopped

### ISSUE THREAD

**Issue by dataprolet** [cirruslabs/tart#967]
I tried to run a stopped VM on a remote host I'm connected to via SSH and got the error that "The number of VMs exceeds the system limit". `tart list` is listing the VM as stopped. After connecting to the remote host via remote desktop I saw that the VM was in fact still running.

Why is `tart list` showing the VM as stopped when they aren't actually stopped?

**EDIT**:
The problem might be that I initially try to start two VMs in the background using the following command:
```
/Applications/tart.app/Contents/MacOS/tart run --net-bridged=en0 vm1 &
/Applications/tart.app/Contents/MacOS/tart run --net-bridged=en0 vm2 &
```
This results in two running VMs, one (vm2) displaying that a computer with the name is already in use on the system. `tart list` is only showing one (vm1, the one without the message) as running.

`tart` is unable to stop vm2 because it is supposedly not running and can also not start it again because of the following error:
`Error Domain=VZErrorDomain Code=2 "Failed to lock auxiliary storage." UserInfo={NSLocalizedFailure=Invalid virtual machine configuration., NSLocalizedFailureReason=Failed to lock auxiliary storage., NSUnderlyingError=0x6000001cfb40 {Error Domain=NSPOSIXErrorDomain Code=35 "Resource temporarily unavailable"}}`

**Comment by edigaryev** [comment]
Which Tart version are you running (the output of `/Applications/tart.app/Contents/MacOS/tart --version`)?

Do I understand correctly that in order to reproduce your scenario, the following lines need to be executed:

```shell
/Applications/tart.app/Contents/MacOS/tart run --net-bridged=en0 vm1 &
/Applications/tart.app/Contents/MacOS/tart run --net-bridged=en0 vm2 &
/Applications/tart.app/Contents/MacOS/tart run --net-bridged=en0 vm3 &
```

For me it results in `vm1` and `vm2` running, and `vm3` not failing to start because of the Apple's macOS VM limit per host.

After running `tart stop vm2`, I can then run `tart run vm3` normally.
